import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./components/header";
import { MobileNav } from "./components/mobileNav";

//titulos
export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"], // escolha os que você quer
  variable: "--font-poppins",
});

//textos
export const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${poppins.variable} ${inter.variable} not-last:antialiased flex flex-col min-h-screen`}
      >
        <Header />
        <div className="p-2 flex-1 max-w-7xl mx-auto w-full pb-30">
          {children}
        </div>
        <div className="fixed bottom-0 left-0 w-full">
          <MobileNav />
        </div>
      </body>
    </html>
  );
}
