import { Metadata } from "next";
import { headers } from "next/headers";
import Image from "next/image";
import Link from "next/link";
import { redirect } from "next/navigation";

import logoImg from "@/app/assets/logo.png";
import { auth } from "@/lib/auth";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  if (session) {
    redirect("/");
  }

  return (
    <section className="flex flex-col items-center justify-center">
      <Link
        href={"/"}
        className="bg-[#3a7d44] w-full rounded-lg p-2 shadow-2xl mb-8"
      >
        <Image src={logoImg} alt="imagem logo" className="mx-auto" />
      </Link>
      {children}
    </section>
  );
}
